name: Deploy

on:
  workflow_dispatch:
    inputs:
      whatIf:
        description: 'Enable WhatIf Mode'
        type: boolean
        required: true
        default: true

jobs:    
  Deployment:
    runs-on: ubuntu-latest
    environment: Development
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: pbi-tools deploy
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "Datasets"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
